import { PROVINCE_IDS } from './ProvinceIds';

export const PROVINCES = PROVINCE_IDS.map(id => {
    const nameMap: Record<string, string> = {
        [PROVINCE_IDS[0]]: "Tarlac",
        [PROVINCE_IDS[1]]: "Zambales",
        [PROVINCE_IDS[2]]: "Abra",
        [PROVINCE_IDS[3]]: "Apayao",
        [PROVINCE_IDS[4]]: "Aurora",
        [PROVINCE_IDS[5]]: "Bataan",
        [PROVINCE_IDS[6]]: "Batanes",
        [PROVINCE_IDS[7]]: "Benguet",
        [PROVINCE_IDS[8]]: "Bulacan",
        [PROVINCE_IDS[9]]: "Cagayan",
        [PROVINCE_IDS[10]]: "Ifugao",
        [PROVINCE_IDS[11]]: "Ilocos Norte",
        [PROVINCE_IDS[12]]: "Ilocos Sur",
        [PROVINCE_IDS[13]]: "Isabela",
        [PROVINCE_IDS[14]]: "Kalinga",
        [PROVINCE_IDS[15]]: "La Union",
        [PROVINCE_IDS[16]]: "Mountain Province",
        [PROVINCE_IDS[17]]: "Nueva Ecija",
        [PROVINCE_IDS[18]]: "Nueva Vizcaya",
        [PROVINCE_IDS[19]]: "Pampanga",
        [PROVINCE_IDS[20]]: "Pangasinan",
        [PROVINCE_IDS[21]]: "Quirino",
        [PROVINCE_IDS[22]]: "Albay",
        [PROVINCE_IDS[23]]: "Batangas",
        [PROVINCE_IDS[24]]: "Camarines Norte",
        [PROVINCE_IDS[25]]: "Camarines Sur",
        [PROVINCE_IDS[26]]: "Catanduanes",
        [PROVINCE_IDS[27]]: "Cavite",
        [PROVINCE_IDS[28]]: "Laguna",
        [PROVINCE_IDS[29]]: "Marinduque",
        [PROVINCE_IDS[30]]: "Masbate",
        [PROVINCE_IDS[31]]: "Metro Manila",
        [PROVINCE_IDS[32]]: "Quezon",
        [PROVINCE_IDS[33]]: "Rizal",
        [PROVINCE_IDS[34]]: "Sorsogon",
        [PROVINCE_IDS[35]]: "Aklan",
        [PROVINCE_IDS[36]]: "Antique",
        [PROVINCE_IDS[37]]: "Biliran",
        [PROVINCE_IDS[38]]: "Bohol",
        [PROVINCE_IDS[39]]: "Capiz",
        [PROVINCE_IDS[40]]: "Cebu",
        [PROVINCE_IDS[41]]: "Eastern Samar",
        [PROVINCE_IDS[42]]: "Guimaras",
        [PROVINCE_IDS[43]]: "Iloilo",
        [PROVINCE_IDS[44]]: "Leyte",
        [PROVINCE_IDS[45]]: "Masbate",
        [PROVINCE_IDS[46]]: "Negros Occidental",
        [PROVINCE_IDS[47]]: "Negros Oriental",
        [PROVINCE_IDS[48]]: "Northern Samar",
        [PROVINCE_IDS[49]]: "Occidental Mindoro",
        [PROVINCE_IDS[50]]: "Oriental Mindoro",
        [PROVINCE_IDS[51]]: "Palawan",
        [PROVINCE_IDS[52]]: "Romblon",
        [PROVINCE_IDS[53]]: "Samar",
        [PROVINCE_IDS[54]]: "Siquijor",
        [PROVINCE_IDS[55]]: "Southern Leyte",
        [PROVINCE_IDS[56]]: "Surigao del Sur",
        [PROVINCE_IDS[57]]: "Tawi-Tawi",
        [PROVINCE_IDS[58]]: "Zamboanga del Norte",
        [PROVINCE_IDS[59]]: "Zamboanga Sibugay",
        [PROVINCE_IDS[60]]: "Agusan del Norte",
        [PROVINCE_IDS[61]]: "Agusan del Sur",
        [PROVINCE_IDS[62]]: "Bukidnon",
        [PROVINCE_IDS[63]]: "Camiguin",
        [PROVINCE_IDS[64]]: "Davao de Oro",
        [PROVINCE_IDS[65]]: "Davao del Norte",
        [PROVINCE_IDS[66]]: "Davao del Sur",
        [PROVINCE_IDS[67]]: "Davao Oriental",
        [PROVINCE_IDS[68]]: "Dinagat Islands",
        [PROVINCE_IDS[69]]: "Lanao del Norte",
        [PROVINCE_IDS[70]]: "Lanao del Sur",
        [PROVINCE_IDS[71]]: "Maguindanao",
        [PROVINCE_IDS[72]]: "Misamis Occidental",
        [PROVINCE_IDS[73]]: "Misamis Oriental",
        [PROVINCE_IDS[74]]: "North Cotabato",
        [PROVINCE_IDS[75]]: "Sarangani",
        [PROVINCE_IDS[76]]: "South Cotabato",
        [PROVINCE_IDS[77]]: "Sultan Kudarat",
        [PROVINCE_IDS[78]]: "Sulu",
        [PROVINCE_IDS[79]]: "Surigao del Norte",
        [PROVINCE_IDS[80]]: "Basilan",
        [PROVINCE_IDS[81]]: "Zamboanga del Sur",
    };

    return { id, val: nameMap[id] || id };
});